### ISSUE TITLE
extends kitbook tsconfig.json

### ISSUE THREAD

**Issue by yellowmachine** [jacob-8/kitbook#12]
When I run `npm run kitbook` it says to add `"extends": "./.svelte-kit-kitbook/tsconfig.json"`
 to tsconfig.json file.

Should I replace my extends value `"./.svelte-kit/tsconfig.json"`?

**Comment by jacob-8** [comment]
This is no longer an issue now that Kitbook is not a side app in the same project. It'll either be part of the main app (recommended) or a separate SvelteKit project that you set up just for a workbench.
