### ISSUE TITLE
integration with tailwindcss

### ISSUE THREAD

**Issue by yellowmachine** [jacob-8/kitbook#13]
Is it possible to see my components with tailwindcss classes applied?

**Comment by yellowmachine** [comment]
I have a file `app.css`:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```
I have added it in my `.md`file:
```ts
import "@/app.css";
```
and it's not exactly what I see in my app but very similar.

**Comment by yellowmachine** [comment]
This is my `DateInput.md`:

```svelte
<script lang="ts">
  import "@/app.css";
  import { Story } from 'kitbook';
  import DateInput from './DateInput.svelte';

  let date = new Date()
</script>

# DateInput

<Story name="show date input" knobs={{label: "Date of birth"}} let:knobs={{label}}>
  <div class="bg-white font-medium text-asteamur-400">  
    <DateInput name={"date"} bind:value={date} {label}  />
    {date}
  </div>
</Story>
```

Maybe I could have a Wrap compoent:

```svelte
<Wrap>
    <DateInput name={"date"} bind:value={date} {label}  />
    {date}
</Wrap>
```

that imports`app.css` and set the style. Is there a better way? Thanks

**Comment by yellowmachine** [comment]
Sorry, there's documentation about [this](https://kitbook.vercel.app/docs/3-customizations/2-app-html);

**Comment by jacob-8** [comment]
Sorry for the long delay. I never responded as the API was changing but wasn't ready yet. If you read through the docs again you'll see that Kitbook is now part of the main app and so Tailwind styles (or any other) will just work.
