### ISSUE TITLE
Instrument Panel doesnt work

### ISSUE THREAD

**Issue by sacrosanctic** [jacob-8/kitbook#17]
# expected

instrument panel should have a input with the label name in which edit the contents of the button

# actual

nothing is shown in instrument panel

# repro

- git clone https://github.com/sacrosanctic/ui-test
- pnpm i
- pnpm dev
- goto http://127.0.0.1:4321/lib/Button

**Comment by jacob-8** [comment]
No longer using instrument panel so I'll close this.
