### ISSUE TITLE
Header styles look strange on mobile

### ISSUE THREAD

**Issue by Brisklemonade** [jacob-8/kitbook#3]
On my IPhone in Safari, the header styles look fine on white backgrounds. However when the background changes it starts to look unpleasant.

![image](https://user-images.githubusercontent.com/71530812/171824045-0f71f5e3-6772-4474-981a-8aa09310f2dc.png)

**Comment by jacob-8** [comment]
The gradient is by design but I may consider doing something more standard like seen on https://vitejs.dev/guide/ - alternatively, https://vitest.dev/guide gives a good example of a blur instead of a gradient to offset the header.

**Comment by Brisklemonade** [comment]
The blur is a nice effect, just remember that it isn't supported by firefox!

**Comment by jacob-8** [comment]
Simplified to white background with border in v0.0.15 - see https://kitbook.vercel.app/1-get-started for example
