### ISSUE TITLE
iFrame support for responsive testing (media queries)

### ISSUE THREAD

**Issue by oneezy** [jacob-8/kitbook#5]

**Comment by jacob-8** [comment]
This would be great! Would you be interested in investigating how Tailwind, Windicss, or [Histoire](https://histoire.dev/) do it and then paste back some example links here for me to be able to use in helping implement this. [Histoire](https://histoire.dev/) supports Svelte so you might want to start there?

**Comment by jacob-8** [comment]
Closing this as all variants and compositions run in iframes now.
